### ISSUE TITLE
Item Saving

### ISSUE THREAD

**Issue by Rushnett** [Pocketkid2/Survival-Games#1]
Players are able to save items in dispensers, furnaces, etc. This allows people playing for a long time to have somewhat of an advantage and makes it unfair to players, since only chests reset when a round finishes.

**Comment by Pocketkid2** [comment]
This is a really great idea. I'll see what I can do.

**Comment by Rushnett** [comment]
Meant to say this was an issue, and not a suggestion (just in case my thing was misinterpreted). I played a game with a bunch of others and noticed that a dispenser had like 4 diamond swords in it haha

**Comment by Pocketkid2** [comment]
It's a system based bug

**Comment by Pocketkid2** [comment]
I'm getting around to working on this, and I had a thought: Would it be cool to have minor loot generate in things such as furnaces and dispensers as well as chests? Would that interest you guys? (as a future feature)

**Comment by KingHorse2015** [comment]
Yes, that would be cool, also coal in furnaces.
