### ISSUE TITLE
message are not loading

### ISSUE THREAD

**Issue by KingHorse2015** [Pocketkid2/Survival-Games#3]
![2015-10-17_16 05 33](https://cloud.githubusercontent.com/assets/15171668/10559126/f5c65ba8-74e8-11e5-96da-04fc5dbd88b3.png)
![2015-10-17_16 05 41](https://cloud.githubusercontent.com/assets/15171668/10559125/f5c62b7e-74e8-11e5-9ab8-26ea72545fbc.png)
message have some problems. i have multiverse, worldedit 6.0 and survival games from you.

- nick

**Comment by Pocketkid2** [comment]
First off don't use /reload as you can see in the chat it doesn't recommend it, this can potentially cause problems. Use PlugMan or /restart.

I'll look into this.

**Comment by KingHorse2015** [comment]
But the plugin works fine. The gameplay and reset. This is the first plugin that works great! Keep up the good work.

**Comment by KingHorse2015** [comment]
![2015-10-18_10 37 16](https://cloud.githubusercontent.com/assets/15171668/10563278/447c9b2c-7584-11e5-80f2-17603e8153b5.png)
it is fixed, what i have done is delete the message file. en restart! the server.

**Comment by KingHorse2015** [comment]
And a message.yml.old file. By the way I am Dutch
